### PR TITLE
Header and body in examples (WIP)

### PR DESCRIPTION
**Pull request by gasparnagy**
As discussed at commit https://github.com/cucumber/gherkin3/commit/e89c30e2ea612d5ac89e93b830c1df3c6a644b95 we switch back to separated Header/Body for examples.

I have created the expected AST files and the .NET code, but have no time now for the other languages, so if anyone want to pick it -> go ahead.

### CODE REVIEW

**Comment by gasparnagy** [comment]
@muhqu could you help on this with the golang?

**Comment by muhqu** [comment]
Can look into it, but probably not before mid next week... Maybe @nightlyone wants to give it a try?

**Comment by brasmusson** [comment]
OK, I have updated the remaining languages to use header and body (also the languages I never written any code in before; go and javascript).

**Comment by gasparnagy** [comment]
@brasmusson fantastic. this project is a great fun for language explorers...

**Comment by aslakhellesoy** [comment]
Awesome @brasmusson

**Comment by muhqu** [comment]
@gasparnagy & @brasmusson :+1: 

@aslakhellesoy I just read through the comments at [`e89c30e`](https://github.com/cucumber/gherkin3/commit/e89c30e2ea612d5ac89e93b830c1df3c6a644b95#commitcomment-10608443) and wanted to reply to your last one...

>  I'm convinced. Feel free to change it to header+body. (I prefer body over rows, but not fussed)

I'm absolutely for the separation of header and body rows, which makes much sense for the *Examples*, but I think the AST elements should better named *TableHeader* + *TableBody*. It's just I think it doesn't feel natural to each over a property solely called "*Body*" to retrieve *Row(s)*... I would expect a property called "*Body*" to refer to a potentially rather large string or byte-type of data. Naming it *TableBody* would make it more obvious what kind of data we're dealing with here...

**Comment by aslakhellesoy** [comment]
I agree @muhqu - feel free to change it

**Comment by mattwynne** [comment]
> I'm absolutely for the separation of header and body rows, which makes much sense for the Examples, but I think the AST elements should better named TableHeader + TableBody. It's just I think it doesn't feel natural to each over a property solely called "Body" to retrieve Row(s)... I would expect a property called "Body" to refer to a potentially rather large string or byte-type of data. Naming it TableBody would make it more obvious what kind of data we're dealing with here…
> 
I agree.

For a DataTable (multiline step argument) can we use TableBody too, or should that be a different type? Headers don’t make sense for those.

**Comment by muhqu** [comment]
@mattwynne sure *TableHeader* doesn't make sense for the *TableData* Step argument. But I don't think that having *TableBody* instead of *Rows* as a property is an improvement.

This is what we have for *TableData* (step argument) now...
``` js
{ type: "Step", ... , argument: {
  type: "DataTable", rows: [ { type: "TableRow", .. }, { type: "TableRow", .. }, ... ]
}}
```

…and this is what I think you're proposing.
``` js
{ type: "Step", ... , argument: {
  type: "DataTable", tableBody: [ { type: "TableRow", .. }, { type: "TableRow", .. }, ... ]
}}
```
 …is that correct @mattwynne?

**Comment by mattwynne** [comment]
Ignore me. I think I was getting confused between types and properties.

**Comment by muhqu** [comment]
@mattwynne :hear_no_evil:

**Comment by muhqu** [comment]
@gasparnagy ur also fine with it as it is?

I think it's ready to get merged and pushed to the subtrees... no?

**Comment by aslakhellesoy** [comment]
LGTM. Do it!

**Comment by muhqu** [comment]
affirmative

**Comment by muhqu** [comment]
`make push-subtrees` :white_check_mark:

**Comment by gasparnagy** [comment]
@muhqu @brasmusson thx!

**Pull request merged**
