### PR TITLE
try to fix travis-ci golang build

### PR DESCRIPTION
**Pull request by muhqu**
please wait until merge for the Pull-Request build to complete

### CODE REVIEW

**Comment by muhqu** [comment]
Waiting for https://travis-ci.org/cucumber/gherkin3/jobs/56704235 to finish... :hourglass_flowing_sand:

**Comment by muhqu** [comment]
:tada: fixed it, pls merge @aslakhellesoy

**Comment by aslakhellesoy** [comment]
Please merge it yourself @muhqu I've given you karma to push to `cucumber/gherkin3`. Also, feel free to work on master for smaller things like this.

**Comment by muhqu** [comment]
@aslakhellesoy thanks a bunch! :bouquet:

**Comment by muhqu** [comment]
@aslakhellesoy doesn't work yet... 
> ERROR: Permission to cucumber/gherkin3.git denied to muhqu.

**Pull request merged**
