### PR TITLE
Support escaped pipe and \n in table cells

### PR DESCRIPTION
**Pull request by koterpillar**
Please be merciless when reviewing this; I'm not fluent in all of the supported languages.

### CODE REVIEW

**Comment by koterpillar** [comment]
Fixes #40.

**Comment by Zearin** [comment]
@koterpillar Looks like there are conflicts.  Can you fix them?

**Comment by koterpillar** [comment]
Done; please tell me if you'd prefer me to rebase.

**Comment by aslakhellesoy** [comment]
Awesome work @koterpillar - spoken like a true polyglot!

**Pull request merged**
