### PR TITLE
(Python) Add compiler

### PR DESCRIPTION
**Pull request by Zearin**
This is a compiler adapted from other implementations (mostly JS, some Java).  

It includes a pathetic test (adapted from Java), and an executable in `bin/`.  

Needs more tests (for sure!)—but it works!

### CODE REVIEW

**Comment by brasmusson** [comment]
Great! Almost there, in https://github.com/cucumber/gherkin3/commit/4fa21ac5af173c2fb5086491bdef8a74e25600ff I updated the Makefile to run the acceptance tests for the compiler, and had to fix two small things one, in the compiler and one in `bin/gherkin-generate-pickles`. Then the acceptance test for the compiler passed: https://travis-ci.org/cucumber/gherkin3/builds/90170604

Without having really read any code in the compiler I can see that [pep8](https://pypi.python.org/pypi/pep8) raise some errors and warning. I have the idea of [keeping the code clean from them](https://github.com/cucumber/gherkin3/blob/master/python/CONTRIBUTING.md#basic-style-guide) (yes, I know a picky, boring comment, but no warnings or errors is nice).

**Comment by Zearin** [comment]
> Great! Almost there, in 4fa21ac I updated the Makefile to run the acceptance tests for the compiler, and had to fix two small things one, in the compiler and one in bin/gherkin-generate-pickles. Then the acceptance test for the compiler passed: https://travis-ci.org/cucumber/gherkin3/builds/90170604

Awesome!  I’ve merged your changes.  Thanks! :)

> Without having really read any code in the compiler I can see that pep8 raise some errors and warning. I have the idea of keeping the code clean from them (yes, I know a picky, boring comment, but no warnings or errors is nice).

Yeah, I know.  

I love the spirit of PEP8, but not how it’s used in the real world. The desire for “no warnings or errors is nice” has taught people to do whatever is necessary to silence those messages, without regard for [the original spirit of PEP8](http://legacy.python.org/dev/peps/pep-0008/#a-foolish-consistency-is-the-hobgoblin-of-little-minds), which recommended that people use their own best judgement when reviewing code according to PEP8 guidelines.  

I love the Python community, but this is something that has always bothered me.  

(Sorry…I had to get that out!  Despite the rant, I’ll have another commit for you soon that will shut the pep8 messages up.)

**Comment by aslakhellesoy** [comment]
I made some changes in 21873b0db02af797abc2f8b98f49f603de74abb8. Can you rebase with master and update the python compiler with the new path stuff please?

**Comment by Zearin** [comment]
> I made some changes in 21873b0. Can you rebase with master and update the python compiler with the new path stuff please?

On it!

**Comment by Zearin** [comment]
Grr!  Failing a test.  Working on it.

**Comment by Zearin** [comment]
Looks to me like the test file `testdata/good/background.feature.pickles.json` does not include the `"path"` key after "name": "Scenario: minimalistic".  

Can you confirm?  I don’t want to mess with the test data unless I’m sure.

**Comment by Zearin** [comment]
(Also, I think this might be the case in the other `testdata/*/*.feature.pickles.json` files as well.  Confirmed?)

**Comment by Zearin** [comment]
Okay!  In #126, I modified the test data to see what happened.  The other tests started failing.

That means that either:

- A pickled scenario should not include a `"path"` key: **OR**
- The non-Python compilers should be updated to add `"path"` to pickled scenarios

**Comment by aslakhellesoy** [comment]
Only the locations of pickles and their steps should have a path. If not it's a bug (possibly in test data)

**Comment by brasmusson** [comment]
The test data is ok, but the current version of the Python compiler has not removed the path from the pickle itself, which https://github.com/cucumber/gherkin3/commit/21873b0db02af797abc2f8b98f49f603de74abb8 did for the other compilers.

**Comment by brasmusson** [comment]
> The desire for “no warnings or errors is nice” has taught people to do whatever is necessary to silence those messages, without regard for the original spirit of PEP8, which recommended that people use their own best judgement when reviewing code according to PEP8 guidelines. 

My selfish reason for wanting to enforce PEP8, is to get help to write in a consistent style from one time to the next. Editors and IDE's can be setup to help you with, or fix, some style and formatting issues, and then it is just as good to make the style they help you with PEP8 compliant. It is nice be able to edit a file someone else wrote and not realizing the your IDE's changed lines unrelated to the lines you changed - when it is trying to help you with the style you asked it to use. On the other hand it is more than possible to write code for which pep8 is silent which is still a lot of problems, is confusing, not working etc. For instance ["meaningful" or "intention-revealing" names](http://www.jbrains.ca/permalink/the-four-elements-of-simple-design) is something your editor/IDE cannot help you with.

**Comment by Zearin** [comment]
> My selfish reason for wanting to enforce PEP8, is to get help to write in a consistent style from one time to the next. Editors and IDE's can be setup to help you with, or fix, some style and formatting issues, and then it is just as good to make the style they help you with PEP8 compliant. It is nice be able to edit a file someone else wrote and not realizing the your IDE's changed lines unrelated to the lines you changed - when it is trying to help you with the style you asked it to use. On the other hand it is more than possible to write code for which pep8 is silent which is still a lot of problems, is confusing, not working etc. For instance "meaningful" or "intention-revealing" names is something your editor/IDE cannot help you with.

I don’t think you were being selfish at all.  

I feel I owe you an apology; on a re-read of my earlier post, it seems as though I were being passive aggressive towards you.  My earlier rant was not directed at anyone in particular; it was simply meant to vent my frustrations from some previous experiences, which had nothing to do with you.  Even as I wrote it—and most certainly after your elaboration above, which I completely agree with—I did not mean to equate you with those experiences.  Sorry for letting my frustrations “leak” into the conversation!

**Comment by Zearin** [comment]
Python compiler now passes the build!  

There’s an unrelated failure in the jRuby build that is keeping this Pull Request’s build status in the red.  From the build log:

```
Installing tins 1.7.0
Gem::InstallError: tins requires Ruby version >= 2.0.
```

In the meantime, is there anything else I can do for the Python compiler?  How’s it look to everyone?

**Comment by aslakhellesoy** [comment]
See #127

**Comment by Zearin** [comment]
Build is good!  (At last! ☺︎)

**Comment by Zearin** [comment]
@aslakhellesoy :D

**Pull request merged**
