### PR TITLE
Add short description comments for TokenScanner

### PR DESCRIPTION
**Pull request by Zearin**
* The description is taken from the README.md
* I looked up the basic rules for “documentation comments” for each language, in order to provide (minimal but functional) support for documentation generators

### CODE REVIEW

**Comment by aslakhellesoy** [comment]
Thanks!

**Comment by Zearin** [comment]
@aslakhellesoy How come you didn’t merge the PR normally?

**Comment by Zearin** [comment]
@aslakhellesoy Never mind!  Apologies.  I could swear that GitHub used to put the red “CLOSED” icon for normal PR merges, and the purple “MERGED” icon for cases when the author manually merged a commit (usually to tweak something about the changes they didn’t like).

Just wanted to make sure that my PRs are up to snuff.  Thanks!

**Comment by aslakhellesoy** [comment]
For small fixes like this I just press GitHub's merge button :-)

**Comment by Zearin** [comment]
Yep!  See my previous comment.  I misunderstood the PR’s status icon.  No worries!

**Pull request merged**
