### PR TITLE
Escaped DocString content

### PR DESCRIPTION
**Pull request by mattwynne**
See https://github.com/cucumber/cucumber-ruby/issues/863#issuecomment-119888052 and https://github.com/cucumber/cucumber-ruby-core/pull/93

I've added what I think is the right failing test, but I'm still hunting around for the right way to implement the solution. Any tips?

### CODE REVIEW

**Comment by brasmusson** [comment]
@mattwynne I would look [here in the token_matcher.rb](https://github.com/cucumber/gherkin3/blob/master/ruby/lib/gherkin3/token_matcher.rb#L72-94) where the normal doc strings tokens are matched.

**Comment by mattwynne** [comment]
Thanks for the clue @brasmusson I think I've nailed that. @gasparnagy @aslakhellesoy can you review before I start trying this on the other languages?

**Comment by mattwynne** [comment]
OK I think this is ready to merge.

**Comment by aslakhellesoy** [comment]
LGTM. Do it!

**Comment by brasmusson** [comment]
Done!

**Pull request merged**
