### PR TITLE
new Parser: golang

### PR DESCRIPTION
**Pull request by muhqu**
first working version passing all the acceptance tests.

still need to cleanup a lot of stuff, but I think this code is ready for others to take it for a spin :rocket: 

btw, amazing how fast it already processes all the acceptance tests:
``` bash
$ cd golang; time make test -B >/dev/null

real	0m0.329s
user	0m0.160s
sys	0m0.166s
```

### CODE REVIEW

**Comment by muhqu** [comment]
@aslakhellesoy I was waiting for the Travis build… now that you merged before it started the build failed. https://travis-ci.org/cucumber/gherkin3/builds/56701654

**Comment by muhqu** [comment]
closely watching https://travis-ci.org/cucumber/gherkin3/jobs/56701951 now ;-)

**Comment by aslakhellesoy** [comment]
Go-rgeous! Absolutely brilliant work.

Out of curiosity - roughly how long did it take you? Was there a particular implementation you used more as a guide than others?

**Comment by muhqu** [comment]
took me about 3 evenings (over the last 2 weeks) + plus some train-hacking… ;-)

I mostly used the Java implementation because of it's type-safety, but also skimmed over the Javascript. I learned a lot about what's considered valid gherkin vs what's not... there are bunch of things where I do not agree, but I wanted to get this thing out to be compliant.

**Comment by muhqu** [comment]
looks like travis is not happy yet with the build matrix: `($GOPATH not set)`

I wonder why there is this large exclusion list. Maybe we should change it to an explicit inclusion matrix?

**Comment by aslakhellesoy** [comment]
What don't you agree with in the grammar? Keep in mind there are hundreds of thousands of people using Gherkin2 (via various Cucumber implementations). Changing the grammar in a non-backwards compatible way would not be very popular.

I agree with you regarding Travis inclusion matrix. Want to help with that?

**Comment by aslakhellesoy** [comment]
Just spotted #11 - you're fast!

**Comment by muhqu** [comment]
@aslakhellesoy just fixed the travis build matrix with 6f0868881de054606d756d56bd3f8a81e01eb7aa, pushing to master also works now. ;-)

**Pull request merged**
