### PR TITLE
Use string functions for left trimming

### PR DESCRIPTION
**Pull request by nightlyone**
since we can get the amount of trimmed text by comparing string lengths.

@muhqu please take a look

### CODE REVIEW

**Comment by muhqu** [comment]
@nightlyone looks like the acceptance tests failed... see [travis](https://travis-ci.org/cucumber/gherkin3/jobs/59880799).

```
diff --unified ../testdata/good/example_tokens_everywhere.feature.tokens acceptance/testdata/good/example_tokens_everywhere.feature.tokens
--- ../testdata/good/example_tokens_everywhere.feature.tokens	2015-04-24 14:09:16.572713965 +0000
+++ acceptance/testdata/good/example_tokens_everywhere.feature.tokens	2015-04-24 14:09:19.926556671 +0000
@@ -9,7 +9,7 @@
 (9:7)TableRow://9:<five>
 (10:1)Empty://
 (11:5)ExamplesLine:Examples//
-(12:7)TableRow://9:one,15:two,22:three,30:four,39:five
-(13:7)TableRow://9:un,15:deux,22:trois,30:quatre,39:cinq
-(14:7)TableRow://9:uno,15:dos,22:tres,30:quatro,39:cinco
+(12:7)TableRow://9:one,14:two,20:three,27:four,35:five
+(13:7)TableRow://9:un,14:deux,20:trois,27:quatre,35:cinq
+(14:7)TableRow://9:uno,14:dos,20:tres,27:quatro,35:cinco
 EOF
```

**Comment by nightlyone** [comment]
Fix is on the way. The make file confused me a bit. It only re-compiles all go files after I did `git clean -d -ff -x` ...

**Comment by muhqu** [comment]
@nightlyone or use `make -B` to unconditionally build everything...

**Comment by muhqu** [comment]
:+1:

**Pull request merged**
